site_name: My Docs
theme:
  name: dracula
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Spanish
      link: /
      lang: es
#  consent:
#    title: Cookie consent
#    description: >- 
#      Aceptar esto no sirve para nada, pero me gusta molestar a la gente con un banner flotante que te obligue a aceptar, asi que acepta :like:
